### ISSUE TITLE
Process capture not working

### ISSUE THREAD

**Issue by poojas2288** [IsmaelHeredia/Fenix_Capture#1]
Currently the process tab returns all the process, therefore if I take the screenshot, it captures a black window on win 7. On win 10, it gives an exception in the function **capturar_ventana** in :  
**var savescreen = new Bitmap(masproceso.v3 - masproceso.v1, masproceso.v4 - masproceso.v2, PixelFormat.Format32bppArgb).**

After debugging, I found that the captured coordinates of **masproceso** are 0
Therefore I cannot capture the process.

Is there a way that I get all the active process only or the active windows ?

**Comment by IsmaelHeredia** [comment]
Yes, I just tried on Windows 7 64-bit and I have the same problem, this program I did in Windows 7 32-bit and I did not have those problems, on Windows 10 I do not have one to test, when I have time and finish other projects will make a fix of this program.

Greetings.

**Comment by poojas2288** [comment]
Is there any update on this ?

**Comment by IsmaelHeredia** [comment]
No, I do not have time because of a lot of work.

**Comment by IsmaelHeredia** [comment]
Well, I took a break and tried to solve the problem.
The problem is that the current applications like firefox and others more use several processes and it is difficult to find which is and what is not.
The update I made sometimes works but it is not a well-done solution.
In the future version of this program I will delete this option of the program because this is deprecated, because there are already two other functions of the program that do the same and do well.

Summary : Process Capture is deprecated.

Best regards.
